# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='street_address',
            field=models.CharField(blank=True, max_length=254, verbose_name='adresse (1\xe8re ligne)'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='street_address2',
            field=models.CharField(blank=True, max_length=254, verbose_name='adresse (2\xe8me ligne)'),
        ),
    ]
