# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_auto_20170806_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoLocation',
        ),
    ]
