# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=254, verbose_name='nom')),
                ('slug', models.SlugField(max_length=254, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, default='default-institution-thumbnail.png', null=True, upload_to='institutions/thumbnail', verbose_name='thumbnail')),
                ('street_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='num. rue')),
                ('street_name', models.CharField(blank=True, max_length=100, verbose_name='nom rue')),
                ('common_name', models.CharField(blank=True, max_length=80, verbose_name='nom commun')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('have_internet', models.BooleanField(default=False, verbose_name='a internet ?')),
                ('number_covers', models.IntegerField(blank=True, default=0, null=True, verbose_name='nombre de couvers')),
                ('number_beds', models.IntegerField(blank=True, default=0, null=True, verbose_name='nombre de lits')),
                ('number_parking_spaces', models.IntegerField(blank=True, default=0, null=True, verbose_name='nombre de places de parking')),
                ('is_accessible_for_hand_m', models.BooleanField(default=False, verbose_name='acc\xe9ssible aux handicap\xe9s \xe0 mobilit\xe9 r\xe9duite ?')),
                ('is_accessible_for_hand_s', models.BooleanField(default=False, verbose_name='acc\xe9ssible aux handicap\xe9s sensoriaux ?')),
                ('number_parking_hn_spaces', models.IntegerField(blank=True, default=0, null=True, verbose_name='nombre de places de parking pour les personnes handicap\xe9s')),
                ('have_metro', models.BooleanField(default=False, verbose_name='a m\xe9tro ?')),
                ('have_bus', models.BooleanField(default=False, verbose_name='a autobus ?')),
                ('have_tramway', models.BooleanField(default=False, verbose_name='a tramway ?')),
                ('have_train', models.BooleanField(default=False, verbose_name='a train ?')),
                ('have_boat', models.BooleanField(default=False, verbose_name='a bateau ?')),
                ('have_other_transport', models.BooleanField(default=False, verbose_name='a transport (autre) ?')),
                ('is_active', models.BooleanField(default=False, verbose_name='est actif ?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date de cr\xe9ation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('commune', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='equipments.Commune')),
                ('special_institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='equipments.SpecialInstitution')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
            },
        ),
    ]
