# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipment_equipmentimage_institutionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activer ?'),
        ),
    ]
