# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20170807_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='activities',
        ),
        migrations.AddField(
            model_name='equipment',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='equipments.SportDiscipline'),
        ),
    ]
