# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='t\xe9l\xe9phone')),
                ('mobile_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='mobile')),
                ('fax_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='fax')),
                ('street_address', models.CharField(blank=True, max_length=254, verbose_name='adresse (1\xe8re ligne)')),
                ('street_address2', models.CharField(blank=True, max_length=254, verbose_name='adresse (2\xe8me ligne)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('N', 'Non sp\xe9cifi\xe9')], default='N', max_length=1, verbose_name='sexe')),
                ('bio', models.TextField(blank=True, max_length=1024, null=True, verbose_name='biographie')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='adresse e-mail confirm\xe9 ?')),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
            },
        ),
    ]
